services:
  - type: web
    name: qservice-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOW-FROM https://web.telegram.org
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    envVars:
      - key: NODE_VERSION
        value: 18.19.1
      - key: API_URL
        value: https://qserver-ii0a.onrender.com/api
      - key: NODE_ENV
        value: production 