services:
  - type: web
    name: qservice-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOW-FROM https://web.telegram.org
      - path: /*
        name: Content-Security-Policy
        value: "default-src * self blob: data: gap:; style-src * self 'unsafe-inline' blob: data: gap:; script-src * 'self' 'unsafe-eval' 'unsafe-inline' blob: data: gap:; object-src * 'self' blob: data: gap:; img-src * self 'unsafe-inline' blob: data: gap:; connect-src self * 'unsafe-inline' blob: data: gap:; frame-src * self blob: data: gap:;"
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    envVars:
      - key: NODE_VERSION
        value: 18.19.1
      - key: API_URL
        value: https://qserver-ii0a.onrender.com/api
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://qserver-ii0a.onrender.com/api
      - key: DEBUG
        value: "true"
      - key: TELEGRAM_APP_ENABLED
        value: "true"
      - key: LOG_LEVEL
        value: "verbose" 